version: '3'

services:

  my-project:
    container_name: my-project
    build:
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    volumes:
      - ./src:/usr/share/nginx/html
    environment:
      - NODE_ENV=${NODE_ENV}
      - SETTING_ENV=development
    ports:
      - '8080:80'
